# Generated by Django 3.2.5 on 2022-04-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='status',
            new_name='active',
        ),
    ]
