# Generated by Django 3.2.5 on 2022-04-16 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_rename_status_client_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='active',
            new_name='converted',
        ),
    ]
